# Code Challenge Make File

Exe: Main.o Equation.o Equations.o EquationsSolver.o FileReader.o
					g++ -o Exe Main.o Equation.o Equations.o EquationsSolver.o FileReader.o

Main.o: Main.cpp
	g++ -c Main.cpp

Equation.o: Equation.cpp
	g++ -c Equation.cpp

Equations.o: Equations.cpp
	g++ -c Equations.cpp

EquationsSolver.o: EquationsSolver.cpp
	g++ -c EquationsSolver.cpp

FileReader.o: FileReader.cpp
	g++ -c FileReader.cpp

clean:
	rm *.o Exe